/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/astronaut/astronaut.gltf --types -T --shadows
*/

import * as THREE from 'three';
import React, { useEffect, useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    AStronoaut_Baked_AStronoaut_Baked_0: THREE.SkinnedMesh;
    AStronoaut_Baked_AStronoaut_Baked_0001: THREE.SkinnedMesh;
    AStronoaut_Baked_AStronoaut_Baked_0002: THREE.SkinnedMesh;
    AStronoaut_Baked_AStronoaut_Baked_0003: THREE.SkinnedMesh;
    AStronoaut_Baked_AStronoaut_Baked_0004: THREE.SkinnedMesh;
    AStronoaut_Baked_AStronoaut_Baked_0005: THREE.SkinnedMesh;
    AStronoaut_Baked_AStronoaut_Baked_0006: THREE.SkinnedMesh;
    AStronoaut_Baked_AStronoaut_Baked_0007: THREE.SkinnedMesh;
    AStronoaut_Baked_AStronoaut_Baked_0008: THREE.SkinnedMesh;
    AStronoaut_Baked_AStronoaut_Baked_0009: THREE.SkinnedMesh;
    AStronoaut_Baked_AStronoaut_Baked_0010: THREE.SkinnedMesh;
    AStronoaut_Baked_AStronoaut_Baked_0011: THREE.SkinnedMesh;
    AStronoaut_Baked_AStronoaut_Baked_0012: THREE.SkinnedMesh;
    AStronoaut_Baked_AStronoaut_Baked_0013: THREE.SkinnedMesh;
    AStronoaut_Baked_AStronoaut_Baked_0014: THREE.SkinnedMesh;
    AStronoaut_Baked_AStronoaut_Baked_0015: THREE.SkinnedMesh;
    AStronoaut_Baked_AStronoaut_Baked_0016: THREE.SkinnedMesh;
    AStronoaut_Baked_AStronoaut_Baked_0017: THREE.SkinnedMesh;
    mixamorigHips: THREE.Bone;
  };
  materials: {
    AStronoaut_Baked: THREE.MeshStandardMaterial;
  };
};

type ActionName = 'Armature|mixamo.com|Layer0';
type GLTFActions = Record<ActionName, THREE.AnimationAction>;

export function Astronaut(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>(null);
  const { nodes, materials, animations } = useGLTF(
    '/models/astronaut/astronaut-transformed.glb'
  ) as GLTFResult;
  const { actions, names } = useAnimations(animations, group);

  useEffect(() => {
    actions[names[0]]?.reset().fadeIn(0.5).play();
  }, []);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh
            name="AStronoaut_Baked_AStronoaut_Baked_0"
            geometry={nodes.AStronoaut_Baked_AStronoaut_Baked_0.geometry}
            material={materials.AStronoaut_Baked}
            skeleton={nodes.AStronoaut_Baked_AStronoaut_Baked_0.skeleton}
          />
          <skinnedMesh
            name="AStronoaut_Baked_AStronoaut_Baked_0001"
            geometry={nodes.AStronoaut_Baked_AStronoaut_Baked_0001.geometry}
            material={materials.AStronoaut_Baked}
            skeleton={nodes.AStronoaut_Baked_AStronoaut_Baked_0001.skeleton}
          />
          <skinnedMesh
            name="AStronoaut_Baked_AStronoaut_Baked_0002"
            geometry={nodes.AStronoaut_Baked_AStronoaut_Baked_0002.geometry}
            material={materials.AStronoaut_Baked}
            skeleton={nodes.AStronoaut_Baked_AStronoaut_Baked_0002.skeleton}
          />
          <skinnedMesh
            name="AStronoaut_Baked_AStronoaut_Baked_0003"
            geometry={nodes.AStronoaut_Baked_AStronoaut_Baked_0003.geometry}
            material={materials.AStronoaut_Baked}
            skeleton={nodes.AStronoaut_Baked_AStronoaut_Baked_0003.skeleton}
          />
          <skinnedMesh
            name="AStronoaut_Baked_AStronoaut_Baked_0004"
            geometry={nodes.AStronoaut_Baked_AStronoaut_Baked_0004.geometry}
            material={materials.AStronoaut_Baked}
            skeleton={nodes.AStronoaut_Baked_AStronoaut_Baked_0004.skeleton}
          />
          <skinnedMesh
            name="AStronoaut_Baked_AStronoaut_Baked_0005"
            geometry={nodes.AStronoaut_Baked_AStronoaut_Baked_0005.geometry}
            material={materials.AStronoaut_Baked}
            skeleton={nodes.AStronoaut_Baked_AStronoaut_Baked_0005.skeleton}
            castShadow
          />
          <skinnedMesh
            name="AStronoaut_Baked_AStronoaut_Baked_0006"
            geometry={nodes.AStronoaut_Baked_AStronoaut_Baked_0006.geometry}
            material={materials.AStronoaut_Baked}
            skeleton={nodes.AStronoaut_Baked_AStronoaut_Baked_0006.skeleton}
          />
          <skinnedMesh
            name="AStronoaut_Baked_AStronoaut_Baked_0007"
            geometry={nodes.AStronoaut_Baked_AStronoaut_Baked_0007.geometry}
            material={materials.AStronoaut_Baked}
            skeleton={nodes.AStronoaut_Baked_AStronoaut_Baked_0007.skeleton}
          />
          <skinnedMesh
            name="AStronoaut_Baked_AStronoaut_Baked_0008"
            geometry={nodes.AStronoaut_Baked_AStronoaut_Baked_0008.geometry}
            material={materials.AStronoaut_Baked}
            skeleton={nodes.AStronoaut_Baked_AStronoaut_Baked_0008.skeleton}
          />
          <skinnedMesh
            name="AStronoaut_Baked_AStronoaut_Baked_0009"
            geometry={nodes.AStronoaut_Baked_AStronoaut_Baked_0009.geometry}
            material={materials.AStronoaut_Baked}
            skeleton={nodes.AStronoaut_Baked_AStronoaut_Baked_0009.skeleton}
            castShadow
          />
          <skinnedMesh
            name="AStronoaut_Baked_AStronoaut_Baked_0010"
            geometry={nodes.AStronoaut_Baked_AStronoaut_Baked_0010.geometry}
            material={materials.AStronoaut_Baked}
            skeleton={nodes.AStronoaut_Baked_AStronoaut_Baked_0010.skeleton}
            castShadow
          />
          <skinnedMesh
            name="AStronoaut_Baked_AStronoaut_Baked_0011"
            geometry={nodes.AStronoaut_Baked_AStronoaut_Baked_0011.geometry}
            material={materials.AStronoaut_Baked}
            skeleton={nodes.AStronoaut_Baked_AStronoaut_Baked_0011.skeleton}
          />
          <skinnedMesh
            name="AStronoaut_Baked_AStronoaut_Baked_0012"
            geometry={nodes.AStronoaut_Baked_AStronoaut_Baked_0012.geometry}
            material={materials.AStronoaut_Baked}
            skeleton={nodes.AStronoaut_Baked_AStronoaut_Baked_0012.skeleton}
            castShadow
          />
          <skinnedMesh
            name="AStronoaut_Baked_AStronoaut_Baked_0013"
            geometry={nodes.AStronoaut_Baked_AStronoaut_Baked_0013.geometry}
            material={materials.AStronoaut_Baked}
            skeleton={nodes.AStronoaut_Baked_AStronoaut_Baked_0013.skeleton}
          />
          <skinnedMesh
            name="AStronoaut_Baked_AStronoaut_Baked_0014"
            geometry={nodes.AStronoaut_Baked_AStronoaut_Baked_0014.geometry}
            material={materials.AStronoaut_Baked}
            skeleton={nodes.AStronoaut_Baked_AStronoaut_Baked_0014.skeleton}
          />
          <skinnedMesh
            name="AStronoaut_Baked_AStronoaut_Baked_0015"
            geometry={nodes.AStronoaut_Baked_AStronoaut_Baked_0015.geometry}
            material={materials.AStronoaut_Baked}
            skeleton={nodes.AStronoaut_Baked_AStronoaut_Baked_0015.skeleton}
          />
          <skinnedMesh
            name="AStronoaut_Baked_AStronoaut_Baked_0016"
            geometry={nodes.AStronoaut_Baked_AStronoaut_Baked_0016.geometry}
            material={materials.AStronoaut_Baked}
            skeleton={nodes.AStronoaut_Baked_AStronoaut_Baked_0016.skeleton}
          />
          <skinnedMesh
            name="AStronoaut_Baked_AStronoaut_Baked_0017"
            geometry={nodes.AStronoaut_Baked_AStronoaut_Baked_0017.geometry}
            material={materials.AStronoaut_Baked}
            skeleton={nodes.AStronoaut_Baked_AStronoaut_Baked_0017.skeleton}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/models/astronaut/astronaut-transformed.glb');
